#!/bin/bash

# Aliases for various Bash commands

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    
    alias ls='ls -lh --color=auto'
    
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
else
    # I don't always use ls, but when I do, I prefer to know the file sizes and
    # modification dates
    alias ls='ls -lh'  
fi

# Other ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# I want to see what's going on when I move and copy
alias cp='cp -v'
alias mv='mv -v'

# A shorter way to get an appropriate git status
# Works best with git 1.7.5+
function gits {
    git status -sb
}

# An updater function so that pulls are fast-forward merged.
function gitup {
    git remote update -p
    git merge --ff-only @{u}
}

