#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        source "$HOME/.bashrc"
    fi
fi

# Brew
PATH="/usr/local/bin:${PATH}"

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Aliases
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# Private Settings
if [ -e "${HOME}/.setup_special" ]; then
    source "${HOME}/.setup_special"
fi

# Default editor
export EDITOR=vim
export VISUAL=vim

# Bind Ctrl-R to history search
bindkey "^R" history-incremental-search-backward

# Use emacs command set
set -o emacs

# Python initial imports
export PYTHONSTARTUP=${HOME}/.pythonrc

